name:  PR fuzzing
on:
  push:
    paths:
      - '**'
permissions: read-all
jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # プライベートリポジトリを指定
          repository: kagomomi/ccwork
          # checkout 先のパスを指定
          path: ./ccwork
          # Personal Access Token を指定
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}


      # プライベートリポジトリの中身を表示してみる
      - run: |
          ls $GITHUB_WORKSPACE
          cd ./main
          touch b
          ls -a
          git status -b
          git config user.name "kagomomi"
          git config user.email "kamo52programing@gmail.com"
          git add .
          git commit -m "generated"
          git push
          
