name:  PR fuzzing
on:
  push:
    paths:
      - '**'
permissions: read-all
jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # プライベートリポジトリを指定
          repository: kagomomi/ccwork
          # checkout 先のパスを指定
          path: ./ccwork
          # Personal Access Token を指定
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main


      # プライベートリポジトリの中身を表示してみる
      - run: |
          touch b
          git config --global user.name kagomomi
          git config --global user.email kamo52programing@gmail.com
          git branch
          git add .
          git commit -m "generated"
          git push
          
